<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WpfApp3.Models\ProjectName.Models.csproj" />
    <ProjectReference Include="..\WpfApp3.Services\ProjectName.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\BlockLeadTabView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\GroupLeadTabView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
